**Projeto desafio 2: administração de condomínios**

A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece. Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio fictício de alguns moradores.

Primeiro passo: abrir a base de dados com Pandas e aplicar o json_normalize no DataFrame.

In [16]:
import pandas as pd
import json

In [17]:
dados_bruto = pd.read_json('/content/dados_locacao_imoveis.json')
dados_bruto

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [18]:
dados_normalizados = pd.json_normalize(dados_bruto['dados_locacao'])
dados_normalizados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

Projeto desafio 2: administração de condomínios
Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, da mesma forma que o projeto 1, o desafio do projeto 2 está listado em algumas metas:

- Remover os dados em listas dentro do DataFrame;
-Verificar os tipos de dados;
-Identificar colunas numéricas;
-Transformar a coluna numérica para o tipo numérico.

In [19]:
# Remover os dados em listas dentro do DataFrame
columns = list(dados_normalizados.columns)
columns

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [20]:
dados_normalizados = dados_normalizados.explode(columns[1:])
dados_normalizados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [21]:
# Verificar os tipos de dados;
# Identificar colunas numéricas;
dados_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.2+ KB

In [22]:
# Transformar a coluna numérica para o tipo numérico.
dados_normalizados['valor_aluguel'] = dados_normalizados['valor_aluguel'].apply(
    lambda x: x.replace('$','').replace(',','.').replace('reais','').strip()
)
dados_normalizados

       apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
0   A101 (blocoAP)                 01/06/2022         05/06/2022        1000.0
0   A101 (blocoAP)                 01/07/2022         03/07/2022        2500.0
1   A102 (blocoAP)                 02/06/2022         02/06/2022        1100.0
1   A102 (blocoAP)                 02/07/2022         06/07/2022        2600.0
2   B201 (blocoAP)                 03/06/2022         07/06/2022        1200.0
2   B201 (blocoAP)                 03/07/2022         03/07/2022        2700.0
3   B202 (blocoAP)                 04/06/2022         07/06/2022        1300.0
3   B202 (blocoAP)                 04/07/2022         05/07/2022        2800.0
4   C301 (blocoAP)                 05/06/2022         10/06/2022        1400.0
4   C301 (blocoAP)                 05/07/2022         09/07/2022        2900.0
5   C302 (blocoAP)                 06/06/2022         08/06/2022        1500.0
5   C302 (blocoAP)                 06/07/2022         12/07/2022        1200.0
6   D401 (blocoAP)                 07/06/2022         07/06/2022        1600.0
6   D401 (blocoAP)                 07/07/2022         09/07/2022        1300.0
7   D402 (blocoAP)                 08/06/2022         10/06/2022        1700.0
7   D402 (blocoAP)                 08/07/2022         14/07/2022        1400.0
8   E501 (blocoAP)                 09/06/2022         10/06/2022        1800.0
8   E501 (blocoAP)                 09/07/2022         09/07/2022        1500.0
9   E502 (blocoAP)                 10/06/2022         16/06/2022        1900.0
9   E502 (blocoAP)                 10/07/2022         12/07/2022        1600.0
10  F601 (blocoAP)                 11/06/2022         17/06/2022        2000.0
10  F601 (blocoAP)                 11/07/2022         13/07/2022        1000.0
11  F602 (blocoAP)                 12/06/2022         15/06/2022        2100.0
11  F602 (blocoAP)                 12/07/2022         12/07/2022        1100.0
12  G701 (blocoAP)                 13/06/2022         19/06/2022        2200.0
12  G701 (blocoAP)                 13/07/2022         20/07/2022        1200.0
13  G702 (blocoAP)                 14/06/2022         15/06/2022        2300.0
13  G702 (blocoAP)                 14/07/2022         17/07/2022        2100.0
14  H801 (blocoAP)                 15/06/2022         18/06/2022        2400.0
14  H801 (blocoAP)                 15/07/2022         16/07/2022        2200.0

In [23]:
import numpy as np

In [24]:
dados_normalizados['valor_aluguel'] = dados_normalizados['valor_aluguel'].astype(np.float64)
dados_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.2+ KB

Projeto desafio 2: administração de condomínios
Na etapa 2, trabalhamos na transformação dos dados numéricos. Agora, podemos trabalhar com valores textuais.

Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.

In [25]:
# Utilizando as \\ Para que elimine os parenteses junto no replace
dados_normalizados['apartamento'] = dados_normalizados['apartamento'].replace('\(blocoAP\)','',regex=True)
dados_normalizados['apartamento']

0     A101
0     A101
1     A102
1     A102
2     B201
2     B201
3     B202
3     B202
4     C301
4     C301
5     C302
5     C302
6     D401
6     D401
7     D402
7     D402
8     E501
8     E501
9     E502
9     E502
10    F601
10    F601
11    F602
11    F602
12    G701
12    G701
13    G702
13    G702
14    H801
14    H801
Name: apartamento, dtype: object

Projeto desafio 2: administração de condomínios
Assim como no projeto desafio 1, trabalhamos com todas as colunas exceto as que envolvem datas.

Nas colunas datas_de_pagamento e datas_combinadas_pagamento, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

Se você não lembra o problema do projeto desafio 2, vou deixar abaixo o texto da situação para facilitar o encontro da informação:

In [33]:
dados_normalizados['datas_de_pagamento'] = pd.to_datetime(dados_normalizados['datas_de_pagamento'],format='%d/%m/%Y' )
dados_normalizados['datas_combinadas_pagamento'] = pd.to_datetime(dados_normalizados['datas_combinadas_pagamento'],format='%d/%m/%Y')
dados_normalizados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.2+ KB

In [40]:
dados_normalizados['dias_atraso'] = (dados_normalizados['datas_de_pagamento'] - dados_normalizados['datas_combinadas_pagamento']).dt.days

In [41]:
dados_normalizados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,dias_atraso
0,A101,2022-06-01,2022-06-05,1000.0,4
0,A101,2022-07-01,2022-07-03,2500.0,2
1,A102,2022-06-02,2022-06-02,1100.0,0
1,A102,2022-07-02,2022-07-06,2600.0,4
2,B201,2022-06-03,2022-06-07,1200.0,4
2,B201,2022-07-03,2022-07-03,2700.0,0
3,B202,2022-06-04,2022-06-07,1300.0,3
3,B202,2022-07-04,2022-07-05,2800.0,1
4,C301,2022-06-05,2022-06-10,1400.0,5
4,C301,2022-07-05,2022-07-09,2900.0,4
5,C302,2022-06-06,2022-06-08,1500.0,2
5,C302,2022-07-06,2022-07-12,1200.0,6
6,D401,2022-06-07,2022-06-07,1600.0,0
6,D401,2022-07-07,2022-07-09,1300.0,2
7,D402,2022-06-08,2022-06-10,1700.0,2
7,D402,2022-07-08,2022-07-14,1400.0,6
8,E501,2022-06-09,2022-06-10,1800.0,1
8,E501,2022-07-09,2022-07-09,1500.0,0
9,E502,2022-06-10,2022-06-16,1900.0,6
9,E502,2022-07-10,2022-07-12,1600.0,2
10,F601,2022-06-11,2022-06-17,2000.0,6
10,F601,2022-07-11,2022-07-13,1000.0,2
11,F602,2022-06-12,2022-06-15,2100.0,3
11,F602,2022-07-12,2022-07-12,1100.0,0
12,G701,2022-06-13,2022-06-19,2200.0,6
12,G701,2022-07-13,2022-07-20,1200.0,7
13,G702,2022-06-14,2022-06-15,2300.0,1
13,G702,2022-07-14,2022-07-17,2100.0,3
14,H801,2022-06-15,2022-06-18,2400.0,3
14,H801,2022-07-15,2022-07-16,2200.0,1

In [42]:
media_atraso = dados_normalizados.groupby(['apartamento'])['dias_atraso'].mean()
media_atraso

apartamento
A101     3.0
A102     2.0
B201     2.0
B202     2.0
C301     4.5
C302     4.0
D401     1.0
D402     4.0
E501     0.5
E502     4.0
F601     4.0
F602     1.5
G701     6.5
G702     2.0
H801     2.0
Name: dias_atraso, dtype: float64